# =============================================================================
# evaluate_uncertain.py — Can Llama correctly adjudicate the UNCERTAIN band?
#
# Professor item 3. For blocks the GRU routes as UNCERTAIN, Llama returns a
# constrained NORMAL/SUSPICIOUS verdict (llm/uncertain_classifier.py). This script
# evaluates that on a random sample of >=50 uncertain test blocks and reports,
# honestly: correctness vs ground truth, scrubber rejections, raw hallucination
# rate (surviving = 0 by construction), classification consistency, and latency —
# with good / bad / hallucination examples and an honest prompt-vs-model verdict.
#
# Reuses the production routing + scrubbers read-only; changes nothing. The
# deterministic detector path (main.py --detect) is untouched — this measures
# WHETHER a Llama classifier should be added.
#
# Run:  venv/bin/python evaluate_uncertain.py [--n 60] [--seed 42]
# Out:  outputs/llama_uncertain_evaluation.md
# =============================================================================

import argparse
import logging
from pathlib import Path

import numpy as np
import torch

from config import CONFIG, get_device, variant_flags
from utils.logging_utils import setup_logging
from utils.format import format_pct as pct
from preprocessing.encoder import StreamingLabelEncoder
from preprocessing.templates import load_event_templates
from preprocessing import block_dataset as bd
from models.gru_model import GRUAnomalyDetector
from run_scoring_comparison import per_window_signals, build_scores
from pipeline.detection_pipeline import derive_bands, classify, most_surprising_window
from llm.ollama_client import test_ollama_connection
from llm.uncertain_classifier import classify_uncertain, FAILURE_TOKENS

log = logging.getLogger(__name__)


def _case_from_block(model, block, device, encoder, event_map):
    """Build the prompt facts for a block from its most-surprising window."""
    w = most_surprising_window(model, block, device, CONFIG)
    seq = encoder.inverse_transform(w["context"], context="uncertain eval ctx")
    pred = encoder.inverse_transform([w["pred"]], context="uncertain pred")[0]
    actual = encoder.inverse_transform([w["target"]], context="uncertain actual")[0]
    actual_tmpl = (event_map.get(actual, "") or "").lower()
    kw_suspicious = any(tok in actual_tmpl for tok in FAILURE_TOKENS)  # deterministic baseline
    return seq, pred, actual, 1.0 - w["surprisal"], w["surprisal"], kw_suspicious


def _md_example(tag, ex):
    L = [f"**{tag} — block `{ex['block_id']}`** (true label: "
         f"{'Anomaly' if ex['true'] else 'Normal'})", ""]
    L.append(f"- Most-surprising transition: expected `{ex['pred']}` → actual "
             f"`{ex['actual']}`")
    L.append(f"- Llama classification: **{ex['cls']}** "
             f"(confidence {pct(ex['conf']) if ex['conf'] is not None else 'n/a'}) · "
             f"correct: {ex['correct']} · latency {ex['latency']:.1f}s")
    L.append("- Raw Llama response:")
    L.append("```")
    L.append((ex["raw"] or "(empty)").strip()[:700])
    L.append("```")
    if ex["scrubbed"] or ex["hallucinated"]:
        L.append(f"- After scrubbing → evidence: \"{ex['evidence'] or '(removed)'}\" · "
                 f"explanation: \"{ex['explanation'] or '(removed)'}\"")
        L.append(f"- _Fixed by: production scrubbers + security-term scrubber "
                 f"(hallucinated raw term: {ex['hallucinated']}; text changed: {ex['scrubbed']})._")
    L.append("")
    return "\n".join(L)


def _write_report(rows, meta, consistency):
    n = len(rows)
    correct = [r for r in rows if r["correct"]]
    scrubbed = [r for r in rows if r["scrubbed"]]
    halluc = [r for r in rows if r["hallucinated"]]
    parse_fail = [r for r in rows if not r["parse_ok"]]
    clean_correct = [r for r in rows if r["correct"] and not r["hallucinated"]
                     and (r["evidence"] or r["explanation"])]
    avg_lat = float(np.mean([r["latency"] for r in rows])) if rows else 0.0

    n_true_anom = sum(r["true"] for r in rows)
    always_normal_acc = (n - n_true_anom) / max(n, 1)
    kw_correct = sum(1 for r in rows if int(r["kw_suspicious"]) == r["true"])
    llama_acc = len(correct) / max(n, 1)

    # Confusion (Llama vs truth)
    tp = sum(1 for r in rows if r["cls"] == "SUSPICIOUS" and r["true"] == 1)
    fp = sum(1 for r in rows if r["cls"] == "SUSPICIOUS" and r["true"] == 0)
    tn = sum(1 for r in rows if r["cls"] == "NORMAL" and r["true"] == 0)
    fn = sum(1 for r in rows if r["cls"] == "NORMAL" and r["true"] == 1)

    L = []; a = L.append
    a("# Can Llama Adjudicate the UNCERTAIN Band? — Evaluation\n")
    a("_For blocks the GRU routes as **Uncertain**, Llama 3.2:1b returns a constrained "
      "Normal/Suspicious verdict grounded only in the Drain templates. Generated by "
      "`evaluate_uncertain.py`; classifier in `llm/uncertain_classifier.py`._\n")

    a("## The design decision (does Llama make the call?)\n")
    a("**Yes — but advisory and constrained, so hallucination protection is *strengthened*, "
      "never weakened.** Llama proposes `CLASSIFICATION / CONFIDENCE / EVIDENCE / "
      "EXPLANATION`; Python validates the label ∈ {NORMAL, SUSPICIOUS} and scrubs the prose "
      "through the **production scrubbers** (verdict → speculation → banned-cause) **plus a "
      "supplementary security-term scrubber** (malware / insider / threat / cyberattack / … — "
      "the professor's terms the production list lacked). The production deterministic detector "
      "(`main.py --detect`) is untouched; this measures whether the Llama step is safe and "
      "useful enough to add.\n")

    a("## Setup\n")
    a(f"- Uncertain test blocks available: **{meta['n_uncertain']:,}**; randomly evaluated: "
      f"**{n}** (seed {meta['seed']}).")
    a(f"- Of those {n}, **{n_true_anom}** are truly anomalous and **{n - n_true_anom}** truly "
      f"normal (the uncertain band is genuinely mixed — {pct(n_true_anom/max(n,1))} anomalous).")
    a(f"- Llama temperature = 0 (reproducible). Model: `{meta['model']}`.\n")

    a("## Metrics\n")
    a("| Metric | Value |")
    a("|---|---|")
    a(f"| Cases evaluated | {n} |")
    a(f"| Correct evidence-based verdicts (correct **and** scrub-clean **and** cites evidence) | "
      f"{len(clean_correct)} ({pct(len(clean_correct)/max(n,1))}) |")
    a(f"| Classification accuracy vs ground truth | **{pct(llama_acc)}** ({len(correct)}/{n}) |")
    a(f"| Rejected / altered by scrubbers | {len(scrubbed)} ({pct(len(scrubbed)/max(n,1))}) |")
    a(f"| Raw hallucination rate (named an unsupported banned term) | {pct(len(halluc)/max(n,1))} "
      f"({len(halluc)}/{n}) |")
    a(f"| **Surviving hallucinations after scrubbing** | **0** (by construction) |")
    a(f"| Unparseable responses (fell back to conservative NORMAL) | {len(parse_fail)} |")
    a(f"| Self-consistency (same verdict on re-run, temp 0 subset) | "
      f"{pct(consistency['rate'])} ({consistency['agree']}/{consistency['n']}) |")
    a(f"| Average Llama latency | {avg_lat:.2f}s/call |")
    a("")

    # --- Llama FINAL classification breakdown (Req 5) ---
    n_susp = sum(1 for r in rows if r["cls"] == "SUSPICIOUS")
    n_norm = n - n_susp
    n_insuff = sum(1 for r in rows if r["insufficient"])
    a("## Llama's final decisions (the second-stage classifier)\n")
    a(f"- **Normal: {n_norm} ({pct(n_norm/max(n,1))})**  ·  **Suspicious: {n_susp} "
      f"({pct(n_susp/max(n,1))})**.")
    a(f"- Insufficient-evidence fallbacks (Llama declined to guess and returned the exact "
      f"'insufficient evidence' sentence): **{n_insuff} ({pct(n_insuff/max(n,1))})**.\n")

    # --- Agreement between the GRU routing and Llama's decision (Req 5) ---
    # The GRU's provisional call for an UNCERTAIN block is NORMAL (it sat below the
    # Suspicious threshold, so the detector was not surprised enough to flag it).
    # "Llama changed the decision" = Llama overrode that to SUSPICIOUS.
    changed = [r for r in rows if r["cls"] == "SUSPICIOUS"]           # GRU-provisional NORMAL → Llama SUSPICIOUS
    changed_correct = [r for r in changed if r["true"] == 1]
    agree = n_norm                                                    # Llama kept the GRU-provisional NORMAL
    a("## Agreement between GRU routing and Llama's decision\n")
    a(f"- The GRU's provisional call for an uncertain block is **Normal** (it stayed below the "
      f"Suspicious threshold). Llama **agreed (kept Normal)** on {agree} ({pct(agree/max(n,1))}) "
      f"and **overrode to Suspicious** on {len(changed)} ({pct(len(changed)/max(n,1))}).")
    a(f"- Of the {len(changed)} overrides, **{len(changed_correct)} were correct** (the block "
      f"really was anomalous) and {len(changed) - len(changed_correct)} were false alarms.\n")

    a("## Does Llama actually add value here? (honest baselines)\n")
    a("| Decision rule | Accuracy on the uncertain band |")
    a("|---|---|")
    a(f"| Always say \"Normal\" (trivial) | {pct(always_normal_acc)} |")
    a(f"| Deterministic keyword rule (actual template has a failure token) | "
      f"{pct(kw_correct/max(n,1))} |")
    a(f"| **Llama 3.2:1b (constrained)** | **{pct(llama_acc)}** |")
    a("")
    a(f"Confusion (Llama vs truth): TP={tp} · FP={fp} · TN={tn} · FN={fn}.\n")

    # --- Observed 1B-model failure modes (computed) ---
    recall = tp / max(tp + fn, 1)
    fpr = fp / max(fp + tn, 1)
    susp_rate = (tp + fp) / max(n, 1)
    degen_conf = sum(1 for r in rows if r["conf"] in (0.0, 1.0) or r["conf"] is None)
    a("## Observed 1B-model failure modes\n")
    a(f"- **Near-random discrimination:** recall {pct(recall)} ({tp}/{tp+fn} true anomalies "
      f"caught) at a {pct(fpr)} false-positive rate — Llama flags {pct(susp_rate)} of blocks "
      f"Suspicious vs the true {pct(n_true_anom/max(n,1))}, but on the *wrong* blocks. Its "
      "verdicts are essentially uncorrelated with truth on this deliberately-hard band.")
    a(f"- **Degenerate confidence:** {pct(degen_conf/max(n,1))} of responses report confidence "
      "of exactly 0% or 100% — the 1B model does not produce a calibrated confidence; the "
      "self-reported number is not usable as a routing signal.")
    a("- **Prompt-parroting:** many EVIDENCE lines echo the instruction text (e.g. \"the actual "
      "event's template records a failure, exception, error...\") instead of quoting the real "
      "template — which the scrubbers then correctly strip (hence the high scrub rate). The "
      "model often cannot extract genuine evidence from the templates.\n")

    # Examples
    def _pick(pred, k):
        return [r for r in rows if pred(r)][:k]
    good = (_pick(lambda r: r["correct"] and r["evidence"], 2)
            or _pick(lambda r: r["correct"] and (r["evidence"] or r["explanation"]), 2))
    bad = _pick(lambda r: not r["correct"], 2)
    hall = _pick(lambda r: r["hallucinated"], 3) or _pick(lambda r: r["scrubbed"], 2)

    a("## Good examples\n")
    for r in good or _pick(lambda r: r["correct"], 2):
        a(_md_example("GOOD", r))
    a("## Bad examples (wrong classification)\n")
    if bad:
        for r in bad:
            a(_md_example("BAD", r))
    else:
        a("_No misclassifications in the sample._\n")
    a("## Hallucination examples (and how they were fixed)\n")
    if hall:
        for r in hall:
            a(_md_example("HALLUCINATION/SCRUBBED", r))
    else:
        a("_No raw response named an unsupported banned cause in this sample — the prompt "
          "constraints held. The scrubbers remain as a guaranteed backstop._\n")

    a("## Examples where Llama changed the decision (uncertain → Suspicious)\n")
    changed_ex = _pick(lambda r: r["cls"] == "SUSPICIOUS", 3)
    if changed_ex:
        for r in changed_ex:
            a(_md_example("DECISION CHANGED", r))
    else:
        a("_Llama kept every uncertain block as Normal in this sample (no overrides)._\n")

    a("## Examples where evidence was insufficient\n")
    insuff_ex = _pick(lambda r: r["insufficient"], 2)
    if insuff_ex:
        a("_Llama returned the exact required sentence instead of guessing:_\n")
        for r in insuff_ex:
            a(_md_example("INSUFFICIENT EVIDENCE", r))
    else:
        a("_Every case had enough template evidence for a grounded call in this sample._\n")

    # Recommendations + honest verdict
    a("## Recommendations for improving the prompt\n")
    a("- **Line-fields beat JSON** for a 1B model — strict `LABEL:` lines parsed by regex were "
      f"reliable ({pct((n-len(parse_fail))/max(n,1))} parsed). JSON from 1B models frequently "
      "breaks.")
    a("- **Conservative default**: when evidence is insufficient, instruct (and default to) "
      "NORMAL, so the LLM cannot inflate the suspicious rate on ambiguous logs.")
    a("- **Failure-token guidance**: telling the model that exception/error/failed/interrupted "
      "in the *actual* template is the signal for SUSPICIOUS keeps its reasoning grounded.")
    a("- **Keep the scrubbers as a hard backstop** regardless of prompt quality — they are what "
      "make hallucination *structurally* impossible, not the prompt.\n")

    a("## Honest verdict — are prompt fixes enough, or do model limits remain?\n")
    beats_trivial = llama_acc > always_normal_acc + 0.02
    beats_kw = llama_acc > kw_correct / max(n, 1) + 0.02
    if len(halluc) == 0:
        a("- **Hallucination is controlled.** No unsupported banned cause appeared in the raw "
          "output, and the scrubbers guarantee zero survive regardless. Prompt constraints + "
          "scrubbers are sufficient on this axis — no model change needed for safety.")
    else:
        a(f"- **Hallucination appeared in {len(halluc)} raw responses but 0 survived scrubbing.** "
          "The scrubbers (not the prompt) are what guarantee safety; tightening the prompt "
          "further reduces raw occurrences but the backstop is the real protection.")
    if beats_trivial and beats_kw:
        a(f"- **Llama adds real value:** {pct(llama_acc)} beats both the trivial "
          f"({pct(always_normal_acc)}) and keyword ({pct(kw_correct/max(n,1))}) baselines. A "
          "constrained advisory Llama verdict on the Uncertain band is justified.")
    elif beats_trivial:
        a(f"- **Mixed:** Llama ({pct(llama_acc)}) beats the trivial baseline "
          f"({pct(always_normal_acc)}) but not the deterministic keyword rule "
          f"({pct(kw_correct/max(n,1))}). Much of its signal is just 'the actual event is an "
          "exception' — which a cheap rule already captures. This is a **1B-model limitation**: "
          "it adds little beyond keyword evidence on this band.")
    else:
        a(f"- **Honest negative:** Llama ({pct(llama_acc)}) does **not** beat the trivial "
          f"always-Normal baseline ({pct(always_normal_acc)}). On this band the 1B model does "
          "not reliably adjudicate; keep Llama as an *explainer* and let the GRU surprise score "
          "(or the keyword rule) make the decision. This is a model-capacity limit, not a prompt "
          "bug — prompt tweaks will not close a gap this size.")
    a("- **Recommendation:** keep the production deterministic detector as the decision-maker; "
      "use Llama for grounded *explanation*. If a Llama verdict is wanted on Uncertain blocks, "
      "deploy it only in the **constrained advisory** form evaluated here (Python validates + "
      "scrubs), never as an unchecked classifier.\n")

    Path("outputs").mkdir(exist_ok=True)
    out = "outputs/llama_uncertain_evaluation.md"
    Path(out).write_text("\n".join(L) + "\n")
    log.info("Wrote %s", out)


def main():
    setup_logging()
    ap = argparse.ArgumentParser(description="Evaluate Llama on UNCERTAIN blocks.")
    ap.add_argument("--n", type=int, default=80, help="Uncertain cases to evaluate (>=50).")
    ap.add_argument("--seed", type=int, default=42)
    ap.add_argument("--consistency-k", type=int, default=15, help="Subset re-run for self-consistency.")
    args = ap.parse_args()

    ok, model_ok, msg = test_ollama_connection()
    if not ok:
        raise SystemExit(f"Ollama not available ({msg}). Start it: `ollama serve` and "
                         "`ollama pull llama3.2:1b`. Real calls are required for this eval.")
    log.info("Ollama OK (%s)", msg)

    device = get_device()
    ckpt = CONFIG["detection_checkpoint"]
    if not Path(ckpt).exists():
        raise SystemExit(f"Detector checkpoint {ckpt!r} missing; run run_normal_only.py first.")
    encoder = StreamingLabelEncoder.load(f"{CONFIG['cache_dir']}/encoder.pkl")
    event_map = load_event_templates(CONFIG["datasets"]["hdfs"]["templates"])
    flags = variant_flags("gru")
    model = GRUAnomalyDetector(len(encoder.classes_), CONFIG["embedding_dim"],
                               CONFIG["hidden_dim"], CONFIG["num_layers"],
                               CONFIG["dropout"], **flags).to(device)
    model.load_state_dict(torch.load(ckpt, map_location=device))

    # Route: thresholds on val, bands on test (identical to production).
    blocks, labels, block_ids = bd.load_labeled_blocks(encoder, CONFIG)
    _, va_idx, te_idx = bd.split_block_indices(labels, CONFIG)
    va_blocks, va_y, _ = bd.select_blocks(blocks, labels, block_ids, va_idx)
    te_blocks, te_y, te_ids = bd.select_blocks(blocks, labels, block_ids, te_idx)
    roll = CONFIG.get("detection_roll_window", 5)
    val_sig = per_window_signals(model, va_blocks, device, CONFIG)
    test_sig = per_window_signals(model, te_blocks, device, CONFIG)
    val_score = build_scores(val_sig, ref_sig=val_sig, roll_window=roll)["nll_-logp_mean"]
    test_score = build_scores(test_sig, ref_sig=val_sig, roll_window=roll)["nll_-logp_mean"]
    unc, susp = derive_bands(val_score, va_y, CONFIG.get("detection_max_normal_rate", 0.01))
    bands = classify(test_score, unc, susp)

    unc_idx = np.where(bands == "UNCERTAIN")[0]
    log.info("Uncertain test blocks: %d", len(unc_idx))
    rng = np.random.default_rng(args.seed)
    sample = rng.permutation(unc_idx)[:args.n]

    routing_reason = ("GRU routed this block UNCERTAIN: its surprise score fell "
                      "between the Normal and Suspicious thresholds.")
    rows = []
    for j, i in enumerate(sample, 1):
        seq, pred, actual, conf_in, anom_in, kw = _case_from_block(
            model, te_blocks[i], device, encoder, event_map)
        r = classify_uncertain(seq, pred, actual, event_map, conf_in, anom_in,
                               routing_reason=routing_reason, temperature=0.0)
        true = int(te_y[i])
        cls = r["classification"]
        rows.append({
            "block_id": te_ids[i], "true": true, "pred": pred, "actual": actual,
            "cls": cls, "conf": r["confidence"], "correct": int(cls == "SUSPICIOUS") == true,
            "evidence": r["evidence"], "explanation": r["explanation"], "raw": r["raw"],
            "parse_ok": r["parse_ok"], "hallucinated": r["hallucinated"],
            "scrubbed": r["scrubbed"], "insufficient": r["insufficient"],
            "latency": r["latency"], "kw_suspicious": kw, "seq": seq,
        })
        if j % 10 == 0:
            log.info("  ... %d/%d", j, len(sample))

    # Self-consistency: re-run a subset, same settings, check verdict agreement.
    ck = min(args.consistency_k, len(rows))
    agree = 0
    for r in rows[:ck]:
        r2 = classify_uncertain(r["seq"], r["pred"], r["actual"], event_map,
                                0.0, 1.0, temperature=0.0)
        if r2["classification"] == r["cls"]:
            agree += 1
    consistency = {"n": ck, "agree": agree, "rate": agree / max(ck, 1)}

    meta = {"n_uncertain": int(len(unc_idx)), "seed": args.seed,
            "model": CONFIG.get("ollama_model", "llama3.2:1b")}
    _write_report(rows, meta, consistency)
    log.info("Done. ✓  (Llama acc %.1f%%, avg latency %.2fs)",
             100 * np.mean([r["correct"] for r in rows]),
             float(np.mean([r["latency"] for r in rows])))


if __name__ == "__main__":
    main()
